# https://beta.ruff.rs/docs/configuration/#using-rufftoml

select = ["F", "E", "W", "I001"]
line-length = 90
show-fixes = false
target-version = "py311"
task-tags = ["TODO", "FIXME"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[isort]
known-first-party = []
known-third-party = []
section-order = [
	"future",
	"standard-library",
	"django",
	"third-party",
	"first-party",
	"local-folder",
]
combine-as-imports = true
split-on-trailing-comma = false
lines-between-types = 1

# [isort.sections]
# "django" = ["django"]
